name: core_app
description: Shared Code between Flutter and AngularDart
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  http: ^0.12.0+1
  rxdart: ^0.20.0
